"""add game_object_scene_appearances table

Revision ID: bd185b7edf5d
Revises: 8056784435d8
Create Date: 2026-03-24 10:07:04.270453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd185b7edf5d'
down_revision: Union[str, Sequence[str], None] = '8056784435d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_object_scene_appearances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_object_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('appearance_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.CheckConstraint("appearance_type IN ('narrative', 'combat_foe', 'item', 'scene_object')", name='ck_gosa_appearance_type'),
    sa.CheckConstraint("source IN ('auto', 'manual')", name='ck_gosa_source'),
    sa.ForeignKeyConstraint(['game_object_id'], ['game_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_object_id', 'scene_id', 'appearance_type', name='uq_gosa_go_scene_type')
    )
    with op.batch_alter_table('game_object_scene_appearances', schema=None) as batch_op:
        batch_op.create_index('ix_gosa_game_object_id', ['game_object_id'], unique=False)
        batch_op.create_index('ix_gosa_scene_id', ['scene_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_object_scene_appearances', schema=None) as batch_op:
        batch_op.drop_index('ix_gosa_scene_id')
        batch_op.drop_index('ix_gosa_game_object_id')

    op.drop_table('game_object_scene_appearances')
    # ### end Alembic commands ###
