"""Random roll resolution for the Lone Wolf game engine.

Pure functions that resolve random-number-table lookups against outcome bands.
Supports phase-embedded random events, scene-exit random routing, and
choice-triggered random outcome tables.

No side effects — callers are responsible for persisting state changes.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from app.engine.meters import apply_endurance_delta, apply_gold_delta, apply_meal_delta
from app.engine.types import CharacterState, ChoiceData, RandomOutcomeData


@dataclass
class PhaseRandomResult:
    """Result of resolving a phase-embedded random roll against an outcome table.

    Attributes:
        roll: The raw roll value that was submitted.
        roll_group: The roll group that was resolved.
        matched_outcome: The RandomOutcomeData row that matched, or None if no
            outcome covered the roll value.
        effects_applied: Sequence of effect dicts describing each meter or
            inventory change that was computed (e.g. gold_change, endurance_change).
        scene_redirect: Target scene_id to navigate to when the matched outcome
            is a ``scene_redirect`` effect, or None otherwise.
        narrative_text: Flavour text from the matched outcome, or None.
        events: Audit event dicts generated by meter functions.
    """

    roll: int
    roll_group: int
    matched_outcome: RandomOutcomeData | None
    effects_applied: list[dict] = field(default_factory=list)
    scene_redirect: int | None = None
    narrative_text: str | None = None
    events: list[dict] = field(default_factory=list)


@dataclass
class ChoiceRandomResult:
    """Result of resolving a choice-triggered random roll against outcome bands.

    Attributes:
        roll: The raw roll value that was submitted.
        target_scene_id: The scene_id the player should be sent to.
        target_scene_number: Human-readable scene number for the target scene.
        narrative_text: Flavour text from the matched band, or None.
        events: Audit event dicts (currently always empty; reserved for future use).
    """

    roll: int
    target_scene_id: int
    target_scene_number: int
    narrative_text: str | None = None
    events: list[dict] = field(default_factory=list)


def resolve_phase_random(
    outcomes: list[RandomOutcomeData],
    roll: int,
    roll_group: int,
    state: CharacterState,
) -> PhaseRandomResult:
    """Resolve a random roll against a phase-embedded outcome table.

    Filters the outcome list to the specified ``roll_group``, finds the row
    where ``roll`` falls within ``[range_min, range_max]`` (inclusive), applies
    the matched effect to ``state``, and returns a :class:`PhaseRandomResult`
    describing what happened.

    Effect types:
    - ``gold_change``: Applies :func:`apply_gold_delta` with ``int(effect_value)``.
    - ``endurance_change``: Applies :func:`apply_endurance_delta`.
    - ``meal_change``: Applies :func:`apply_meal_delta`.
    - ``item_gain``: Records an event for the service layer to fulfil; does NOT
      mutate ``state.items``.
    - ``item_loss``: Records an event for the service layer to fulfil; does NOT
      mutate ``state.items``.
    - ``scene_redirect``: Sets ``scene_redirect`` on the result to
      ``int(effect_value)``; the service layer navigates the player.

    Args:
        outcomes: All random outcome rows for the current scene/phase.
        roll: The roll value submitted by the player (0-9 random number table).
        roll_group: Which roll group to resolve (used for multi-roll scenes).
        state: Current character state snapshot.

    Returns:
        A :class:`PhaseRandomResult` with all resolved effects and events.
    """
    group_outcomes = [o for o in outcomes if o.roll_group == roll_group]

    matched: RandomOutcomeData | None = None
    for outcome in group_outcomes:
        if outcome.range_min <= roll <= outcome.range_max:
            matched = outcome
            break

    if matched is None:
        return PhaseRandomResult(
            roll=roll,
            roll_group=roll_group,
            matched_outcome=None,
        )

    effects_applied: list[dict] = []
    all_events: list[dict] = []
    scene_redirect: int | None = None

    effect_type = matched.effect_type
    effect_value = matched.effect_value

    if effect_type == "gold_change":
        delta = int(effect_value)
        new_gold, actual_delta = apply_gold_delta(state, delta)
        effects_applied.append(
            {"type": "gold_change", "delta": delta, "actual": actual_delta, "new_gold": new_gold}
        )

    elif effect_type == "endurance_change":
        delta = int(effect_value)
        new_end, is_dead, events = apply_endurance_delta(state, delta)
        effects_applied.append(
            {
                "type": "endurance_change",
                "delta": delta,
                "new_endurance": new_end,
                "is_dead": is_dead,
            }
        )
        all_events.extend(events)

    elif effect_type == "meal_change":
        delta = int(effect_value)
        new_meals, actual_delta = apply_meal_delta(state, delta)
        effects_applied.append(
            {
                "type": "meal_change",
                "delta": delta,
                "actual": actual_delta,
                "new_meals": new_meals,
            }
        )

    elif effect_type == "item_gain":
        event: dict = {"type": "item_gain", "item_name": effect_value}
        effects_applied.append(event)
        all_events.append(event)

    elif effect_type == "item_loss":
        event = {"type": "item_loss", "item_name": effect_value}
        effects_applied.append(event)
        all_events.append(event)

    elif effect_type == "scene_redirect":
        scene_redirect = int(effect_value)
        effects_applied.append({"type": "scene_redirect", "target_scene_id": scene_redirect})

    return PhaseRandomResult(
        roll=roll,
        roll_group=roll_group,
        matched_outcome=matched,
        effects_applied=effects_applied,
        scene_redirect=scene_redirect,
        narrative_text=matched.narrative_text,
        events=all_events,
    )


def resolve_scene_exit_random(choices: list[ChoiceData], roll: int) -> int | None:
    """Resolve a random roll against scene-exit choices to determine navigation target.

    All choices in ``choices`` are expected to have ``condition_type="random"``
    and a ``condition_value`` formatted as ``"min-max"`` (e.g. ``"0-4"``).
    The inclusive range ``[min, max]`` is parsed and the first matching choice's
    ``target_scene_id`` is returned.

    Args:
        choices: Scene choices gated by random range conditions.
        roll: The roll value to match against.

    Returns:
        The ``target_scene_id`` of the matched choice, or ``None`` if no choice
        covers the roll value.
    """
    for choice in choices:
        if choice.condition_value is None:
            continue
        try:
            low_str, high_str = choice.condition_value.split("-", 1)
            low = int(low_str)
            high = int(high_str)
        except (ValueError, AttributeError):
            continue
        if low <= roll <= high and choice.target_scene_id is not None:
            return choice.target_scene_id

    return None


def resolve_choice_triggered_random(
    outcome_bands: list[dict],
    roll: int,
) -> ChoiceRandomResult:
    """Resolve a roll against a choice's outcome bands to determine the destination scene.

    Each band dict must contain:
    - ``range_min`` (int): Inclusive lower bound of the band.
    - ``range_max`` (int): Inclusive upper bound of the band.
    - ``target_scene_id`` (int): The scene_id to navigate to.
    - ``target_scene_number`` (int): Human-readable scene number.
    - ``narrative_text`` (str | None): Optional flavour text for the band.

    Args:
        outcome_bands: Ordered list of band dicts from the choice's random outcome table.
        roll: The roll value to match against.

    Returns:
        A :class:`ChoiceRandomResult` for the matched band.

    Raises:
        ValueError: If no band covers the provided roll value.
    """
    for band in outcome_bands:
        if band["range_min"] <= roll <= band["range_max"]:
            return ChoiceRandomResult(
                roll=roll,
                target_scene_id=band["target_scene_id"],
                target_scene_number=band["target_scene_number"],
                narrative_text=band.get("narrative_text"),
                events=[],
            )

    raise ValueError(f"Roll {roll} did not match any outcome band.")


def get_roll_groups(outcomes: list[RandomOutcomeData]) -> list[int]:
    """Return the sorted unique roll group numbers present in an outcome list.

    Used by the API to determine how many sequential rolls are required before
    the scene's random phase is complete.

    Args:
        outcomes: All random outcome rows for a scene or phase.

    Returns:
        Sorted list of unique ``roll_group`` values.
    """
    return sorted({o.roll_group for o in outcomes})


def has_remaining_rolls(
    outcomes: list[RandomOutcomeData],
    completed_groups: list[int],
) -> tuple[bool, int | None]:
    """Determine whether more rolls are needed and which group comes next.

    Args:
        outcomes: All random outcome rows for the scene or phase.
        completed_groups: Roll group numbers that have already been resolved.

    Returns:
        A two-tuple of:
        - ``has_more`` (bool): True when at least one group has not been rolled.
        - ``next_group`` (int | None): The lowest unresolved group number, or
          ``None`` when all groups are complete.
    """
    all_groups = get_roll_groups(outcomes)
    completed_set = set(completed_groups)
    remaining = [g for g in all_groups if g not in completed_set]
    if remaining:
        return True, remaining[0]
    return False, None
